// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MagiQL")]
[assembly: AssemblyVersionAttribute("2.0.14")]
[assembly: AssemblyFileVersionAttribute("2.0.14")]
[assembly: AssemblyInformationalVersionAttribute("2.0.14")]
[assembly: AssemblyCompanyAttribute("Salesforce")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.14";
        internal const string InformationalVersion = "2.0.14";
    }
}
